# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPA
version:      1.04
version_from: IPA.pm
installdirs:  site
requires:
    Prima:                         1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
